name: Compilar Flix_ff.mm. iOS
on: 
  push:
  workflow_dispatch: # Ativa o botão manual

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Compilar Dylib
        run: |
          clang -dynamiclib -arch arm64 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -o Flix_ff.dylib Flix_ff.mm \
          -framework Foundation -framework UIKit \
          -lobjc

      - name: Salvar Arquivo Compilado
        uses: actions/upload-artifact@v4 # Versão atualizada que corrige o erro
        with:
          name: Flix_ff_Dylib
          path: Flix_ff.dylib
