name: Compilar Flix_ff iOS
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Localizar e Preparar Script
        run: |
          # Procura o arquivo Flix_ff.mm e o move para a raiz, caso esteja em pasta errada
          find . -name "Flix_ff.mm" -exec cp {} . \;
          ls -la # Lista os arquivos para confirmar a presença do script

      - name: Compilador Dylib
        run: |
          clang -dynamiclib -arch arm64 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -o Flix_ff.dylib Flix_ff.mm \
          -framework Foundation -framework UIKit \
          -lobjc

      - name: Salvar Arquivo Compilado
        uses: actions/upload-artifact@v4
        with:
          name: Flix_ff_Dylib
          path: Flix_ff.dylib
