name: Compilar Flix_ff iOS
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Localizar Script e Baixar Dependências
        run: |
          # Garante que o script está na raiz
          find . -name "Flix_ff.mm" -exec cp {} . \;
          
          # Baixa a biblioteca Substrate que está faltando
          curl -LO https://github.com/Dherton/mshook-ios/raw/master/substrate.h
          ls -la # Confirma se o substrate.h e o Flix_ff.mm estão aqui

      - name: Compilador Dylib
        run: |
          clang -dynamiclib -arch arm64 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -I. \
          -o Flix_ff.dylib Flix_ff.mm \
          -framework Foundation -framework UIKit \
          -lobjc

      - name: Salvar Arquivo Compilado
        uses: actions/upload-artifact@v4
        with:
          name: Flix_ff_Dylib
          path: Flix_ff.dylib
